mybot:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  
  

  # Effort Controllers ---------------------------------------
  left_back_Wheel_effort_controller:
    type: effort_controllers/JointEffortController
    joint: left_back_wheel_hinge
    pid: {p: 100.0, i: 0.1, d: 10.0}
  right_back_Wheel_effort_controller:
    type: effort_controllers/JointEffortController
    joint: right__back_wheel_hinge
    pid: {p: 100.0, i: 0.1, d: 10.0}
